blog/urls.py
from django.conf.urls import include,url
from . import views

urlpatterns = [
	url(r'^$',views.post_list, name="list"),
    url(r'^create/$', views.post_create),
    url(r'(?P<pk>\d+)/$', views.post_detail, name='detail'),
    url(r'(?P<pk>\d+)/edit/$', views.post_update,name="update"),
    url(r'^delete/$', views.post_delete)
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

from . import views
from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^$', views.home, name="home"),
    url(r'^about_me', views.about_me, name="about_me"),
    url(r'^contact', views.contact, name="contact"),
    #url(r'', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
	url(r'^$',views.project_list, name="list"),
	url(r'^create/$', views.project_create),
	url(r'(?P<pk>\d+)/$',views.project_detail,name='detail'),
    url(r'(?P<pk>\d+)/edit/$', views.project_update, name="update"),
    url(r'^delete/$', views.project_delete),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
import datetime
import markdown

from django.db import models
from django.utils import timezone
from django.conf import settings

def markdown_to_html( markdownText): #, images ):
    image_ref = ""

    #for image in images:
    #    image_url = settings.MEDIA_URL + image.image.url
    #    image_ref = "%s\n[%s]: %s" % ( image_ref, image, image_url )

    md = "%s\n%s" % ( markdownText, image_ref )
    html = markdown.markdown( md )

    return html

class Image( models.Model ):
    name = models.CharField( max_length=100 )
    image = models.ImageField( upload_to="images" )

    def __unicode__( self ):
        return self.name

class Project(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(default ='',max_length=255)
    subject = models.CharField(default='',max_length=255)
    thumbnail = models.ImageField(upload_to="images", default='images/question.jpg') #, null=True, blank=True, )
    body = models.TextField(default='')
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ['order']

    def get_absolute_url(self):
        return "/projects/{}".format(self.id)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def body_html( self ):
        return markdown_to_html( self.body) # self.images.all() )

projects/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Project


class ProjectForm(forms.ModelForm):
    body = forms.CharField(widget=PagedownWidget)
    #publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Project
        fields = (
            "title",
            "author",
            "subject",
            "body",
            "thumbnail",
            "order",
        )

projects/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib import messages

from .models import Project
from .forms import ProjectForm


def project_create(request):
    print("Files request:", request.FILES)
    print("Files post:", request.POST)

    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    form = ProjectForm(request.POST or None)

    if request.method == 'POST':


        form = ProjectForm(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect(instance.get_absolute_url())

        context = {
            "form":form,
        }
        return render(request, "projects/project_form.html", context)
    context = {
        "form": form,
    }
    return render(request, "projects/project_form.html", context)

def project_detail(request,pk):
    project = get_object_or_404(Project,pk=pk)
    return render(request,'projects/project_detail.html',{'project':project})


def project_delete(request, pk):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Project, pk=pk)
    instance.delete()
    messages.success(request, "successfully deleted")


def project_list(request):
    projects = Project.objects.all() #filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'projects/project_list.html', {'projects': projects})


def project_update(request, pk):
    print("Files request:", request.FILES)
    print("Files post:", request.POST)
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Project, pk=pk)

    form = ProjectForm(request.POST or None, instance=instance)

    if request.method == 'POST':

        form = ProjectForm(request.POST, request.FILES,instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "form": form,
        "title": instance.title,
        "instance": instance,
        }
    return render(request, 'projects/project_form.html', context)

    #form = ProjectForm(request.POST or None, instance=instance)
    #if form.is_valid():
    #    instance = form.save(commit=False)
     #   instance.save()
        #message success
      #  return HttpResponseRedirect(instance.get_absolute_url())

projects/templates/projects/project_detail.html
{% extends "layout.html" %}

{% block title %}{{ project.title }}{% endblock %}

{% block content %}
<div class="skinny-read">
    <h3>{{ project.title }}</h3>
    </br>
    <section>
        
        {{ project.body_html|safe }}
     
    </section>
</div>
{% endblock %}

projects/templates/projects/project_form.html
{% extends "layout.html" %}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}


{% block content %}
<div class="col-sm-6 col-sm-offset-3">
    <h1>Form</h1>

    <form method='POST' action='.' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' class="btn btn-default" value="Create Project" />
    </form>
</div>
{% endblock content %}

projects/templates/projects/project_list.html
{% extends "layout.html" %}

{% block title %}Projects{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-8">
        <header class='page-header'>
            <h2>Welcome to my Projects Page.</h2>
            <p>I am using this webpage to showcase some of the projects I'm working on right now. Take a look around and explore!</p>
        </header>
        {% for project in projects %}
        <article>
            <p>
                <a href="{% url 'projects:detail' pk=project.pk %}">
                    <img class = "thumbnail" src="{{ project.thumbnail.url }}" alt="Project_thumbnail" width="275" height="183" border="0"/>
                </a>
            </p>
            <h3>
                <a href="{% url 'projects:detail' pk=project.pk %}">{{ project.title }}</a>
                <span aria-hidden="true" class="octicon octicon-link"></span>
            </h3>

            <p class="anchor">{{ project.subject }}</p>
            <a class="btn btn-default btn-xs" href="{% url 'projects:detail' pk=project.pk %}">More ...</a>
            <hr>
        </article>
        {% endfor %}
    </div>
</div>

{% endblock %}