blog/urls.py
from django.conf.urls import include,url
from . import views

urlpatterns = [
	url(r'^$',views.post_list, name="list"),
    url(r'^create/$', views.post_create),
    url(r'(?P<pk>\d+)/$', views.post_detail, name='detail'),
    url(r'(?P<pk>\d+)/edit/$', views.post_update,name="update"),
    url(r'^delete/$', views.post_delete)
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

from . import views
from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^$', views.home, name="home"),
    url(r'^about_me', views.about_me, name="about_me"),
    url(r'^contact', views.contact, name="contact"),
    #url(r'', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/about_me.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}About Me{% endblock %}


{% block content %}



<div class="row">
    <div class="col-lg-4">
        <img src="{% static 'images/me.jpg' %}" ALT="ME" WIDTH=200 HEIGHT=250 class="center-block aboutpic">
    </div>
    <div class="col-lg-8">
        <h1 class="aboutme">Griffin Cleverly</h1>
        </br>
        <p class="aboutm">
            Hi! My name is Griffin Cleverly. I'm a Mechanical Engineer with a passion for coding living in Los Angeles.
            I tend to focus on projects that use Python, especially if they involve data or web development.
            In my spare time you might find me surfing, hiking, or rooting for UCLA sports teams.
            I'm into traveling and enjoy talking about everything from the news to sports to food.
            Take a look at my site and let's get in contact!
        </p>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">


    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">

        <h4>EDUCATION</h4>
        <dl class="field">
            <dt>University of California, Los Angeles</dt>
            <dd>B.S. Mechanical Engineering</dd>
        </dl>
        </br>
        <h4>EXPERIENCE</h4>
        <dl class="field">
            <dt>Proposal Design Engineer</dt>
            <dd>Thermal Engineering International</dd>
            <dt>Magzor Robotics</dt>
            <dd>Mechanical Engineering Intern</dd>
        </dl>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">

        <h4>CAPABILITIES</h4>
        <dt>Web Development</dt>
        <dd>CSS</dd>
        <dd>HTML</dd>
        <dd>Javascript</dd>
        <dd>Django</dd>
        <dt>Languages</dt>
        <dd>Python<dd>
        <dd>Java<dd>
        <dd>C++<dd>
        <dd>Matlab<dd>
        <dt>Databases</dt>
        <dd>MySQL<dd>
        <dd>MongoDB<dd>
        <dd>PostgreSQL<dd>
    </div>

</div>
{% endblock content %}

templates/contact.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% block title %}Contact Me{% endblock %}


{% block content %}

<header class='page-header'>

<h2>Let's get in touch</h2>

</header>
<p>You can contact me through the following:</p>
	<ul><a href="mailto:gtcleverly@gmail.com?Subject=Web%20Site%20Hello"><i class="fa fa-envelope fa-lg"></i> E-mail</a></ul>
	<ul><a href="https://github.com/gcleverly"><i class="fa fa-github fa-lg"></i> Github Profile</a></ul>
	<ul><a href="https://linkedin.com/in/griffincleverly"><i class="fa fa-linkedin-square fa-lg"></i> LinkedIn Profile</a></ul>
</p>









{% endblock content %}

templates/home.html
<!doctype html>
{% load static from staticfiles %}

<html>
	<head>
		<title>Griffin Cleverly's Website</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/blog-post.css' %}">
	</head>
	<body background="{% static 'images/ceystalhorizon.png' %}">
			
	<div class="frontpage">
		<h1>GRIFFIN CLEVERLY</h1>
		<span><a href="{% url 'projects:list' %}">PROJECTS</a> | </span>
		<span><a href="{% url 'about_me' %}">ABOUT ME</a> | </span>
		<span><a href="{% url 'contact' %}">CONTACT</a></span>
	</div>
	<footer>

	</footer>
</body>
</html>

templates/layout.html
<!DOCTYPE html>
{% load static from staticfiles %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!--<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">-->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" type="text/css">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-post.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head_extra %} {% endblock head_extra %}
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">Griffin Cleverly</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'about_me' %}">About</a>
                </li>
                <li >
                    <a href="{% url 'projects:list' %}">Projects</a>
                </li>
                <li>
                    <a href="{% url 'blog:list' %}">Blog</a>
                </li>
                <li >
                    <a href="{% url 'contact' %}">Contact</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'blog:list' %}"><i class="fa fa-th-list"></i><span class="icon-label">Archives</span></a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
<!-- /.navbar -->
<div class="container">
    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Griffin Cleverly 2016</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>

</div>

<!-- jQuery -->
<script src="{% static 'js/jquery.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>